### ISSUE TITLE
Dont work anymore mabe fix? idk

### ISSUE THREAD

**Issue by 0x33c** [SMVampire/SteamBotDev#6]
i have some issues with this methode. i think it dont work anymore.

After i get the backup and i want to extract the backup i got a 1kb .tar and this is broken i cant open it in winrar 7zip...

after try to backup only the steam app adb shell say -> Package 'com.valvesoftware.android.steam.community' is not debuggable

R.I.P. steam app 2017

**Comment by SMVampire** [comment]
I didn't write it, I just shared it. I unfortunately can't do anything to fix it.
